---
# tasks file for screenshot
- name: install dependencies
  become: true
  pacman:
    name: "{{ screenshot_packages }}"

- name: copy eww config
  copy:
    src: home/.config/eww
    dest: ~/.config
