---
# tasks file for env
- name: Setup .profile to use .config/profile.d
  ansible.builtin.blockinfile:
    path: ~/.profile
    create: true
    mode: '0644'
    marker: '# {mark} ANSIBLE MANAGED BLOCK @profile.d'
    block: |
      # Load profiles from ~/.config/profile.d
      if test -d ~/.config/profile.d; then
          for profile in ~/.config/profile.d/*.sh; do
              test -r "$profile" && . "$profile"
          done
          unset profile
      fi
