---
# tasks file for rust
# https://www.rust-lang.org/tools/install
- name: install build dependencies
  become: true
  pacman:
    name:
      - curl
      - base-devel
    extra_args: --needed

- name: check that the Cargo already local installed
  stat:
    path: ~/.cargo/bin
  register: cargo_stat_result

- name: install Rust
  shell: |
    set -o pipefail
    curl --proto '=https' --tlsv1.2  https://sh.rustup.rs -sSf | sh -s -- -y
  when: cargo_stat_result.stat.exists == false
