---
- name: "Install and set Icon Theme"
  ansible.builtin.include_tasks: "{{ gnome_appearance_icon_theme_map[gnome_appearance_icon_theme] }}/main.yml"

- name: "Set Icons, GTK and Gnome Shell theme"
  community.general.dconf:
    key: "/org/gnome/desktop/interface/icon-theme"
    value: "'{{ gnome_appearance_icon_theme }}'"

- name: "Set GDM icon theme"
  become: true
  command: "sudo -u gdm dbus-launch gsettings set org.gnome.desktop.interface icon-theme '{{ gnome_appearance_icon_theme }}'"
  changed_when: false
