---
# tasks file for bluetooth
- name: install dependencies
  become: true
  community.general.pacman:
    name: '{{ bluetooth_packages }}'

- name: add the user to 'lp' group
  become: true
  user:
    name: '{{ ansible_user_id }}'
    groups: lp
    append: yes

- name: enable bluetooth service
  become: true
  systemd:
    name: bluetooth.service
    state: started
    enabled: yes
