---
# tasks file for reflector
- name: Install dependencies
  become: true
  community.general.pacman:
    name: '{{ reflector_packages }}'

- name: Setup country
  become: true
  ansible.builtin.lineinfile:
    path: /etc/xdg/reflector/reflector.conf
    regexp: '^# --country France,Germany'
    line: '--country Russia,Germany'

- name: Setup repo count
  become: true
  ansible.builtin.lineinfile:
    path: /etc/xdg/reflector/reflector.conf
    regexp: '^--latest 5'
    line: '--latest 20'

- name: Enable reflector service
  become: true
  ansible.builtin.systemd:
    name: reflector.service
    enabled: true

- name: Enable mirror list update schedule.
  become: true
  ansible.builtin.systemd:
    name: reflector.timer
    state: started
    enabled: true
