---
# tasks file for applications
- include_tasks: applications/firefox.yml
#
- name: Configure custom keyboard shortcuts for applications
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    # List of keybindings
    - key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
      value:
        "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/tilix-quake-mode/',
        '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/keychron-k3-fn-on/',
        '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/keychron-k3-fn-off/'
        ]"
    # Tilix quake mode
    - key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/tilix-quake-mode/name"
      value: "'Tilix Quake mode'"
    - key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/tilix-quake-mode/command"
      value: "'tilix --quake'"
    - key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/tilix-quake-mode/binding"
      value: "'<Ctrl><Shift>space'"
    # Keychron K3 Fn On
    - key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/keychron-k3-fn-on/name"
      value: "'Keychron K3 Fn On'"
    - key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/keychron-k3-fn-on/command"
      value: "'bash -c 'kbd-set-fn-mode 0 && notify-send -i ibus-keyboard \"Fn keys on\" \"Now you can use functional keys\"''"
    - key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/keychron-k3-fn-on/binding"
      value: "'<Alt>E'"
    # Keychron K3 Fn Off
    - key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/keychron-k3-fn-off/name"
      value: "'Keychron K3 Fn Off'"
    - key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/keychron-k3-fn-off/command"
      value: "'bash -c 'kbd-set-fn-mode 1 && notify-send -i keyboard \"Fn keys off\" \"Now you can use media keys\"''"
    - key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/keychron-k3-fn-off/binding"
      value: "'<Alt>D'"

- name: configure favorite apps
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - key: "/org/gnome/shell/favorite-apps"
      value: "['firefox.desktop', 'org.gnome.Nautilus.desktop', 'com.gexperts.Tilix.desktop']"
