---
# tasks file for tlp
- name: install dependencies
  become: true
  pacman:
    name: "{{ tlp_packages }}"

# GNOME 40 and newer
- name: mask the Gnome power-profiles-daemon service
  become: true
  systemd:
    name: power-profiles-daemon.service
    state: stopped
    masked: true

- name: enable tlp service
  become: true
  systemd:
    name: tlp.service
    state: started
    enabled: yes

- name: mask rfkill service
  become: true
  systemd:
    name: systemd-rfkill.service
    state: stopped
    masked: true

- name: mask rfkill socket
  become: true
  systemd:
    name: systemd-rfkill.socket
    state: stopped
    masked: true

- name: enable NetworkManager-dispatcher service
  become: true
  systemd:
    name: NetworkManager-dispatcher.service
    state: started
    enabled: yes
