---
# This playbook deploys the whole application stack.
- name: Apply common configuration to all nodes
  hosts: all
  roles:
    # System folders
    ## Setup $PATH
    - role: environment/path
    ## Setup XDG basedir
    - environment/xdg_basedir

    # Package management
    ## Update package database
    - role: package-management/update
    ## Setup pacman mirror list
    - role: package-management/reflector
    ## Setup AUR helper
    - role: package-management/build_tools
    - role: package-management/paru
    ## Upgrade system
    - role: package-management/upgrade

    # Default CLI editor
    - role: environment/default_cli_text_editor

    # Linux Kernels
    - role: kernels/linux
      tags:
        - laptop
        - desktop
    - role: kernels/linux_lts
      tags:
        - virtualbox
    - role: kernels/linux_lqx
      tags:
        - av-production

    # Hardware
    ### Network
    - role: hardware/networkmanager
    ### Sound card firmware
    - role: hardware/sof_firmware
      tags:
        - laptop
        - desktop
    ### Audio
    - role: hardware/pipewire
      tags:
        - laptop
        - desktop
    ### Bluetooth
    - role: hardware/bluez
      tags:
        - laptop
        - desktop
    ### Power management
    - role: hardware/tlp
      tags:
        - laptop

    # Languages and Localization
    # TODO: locale variables
    # TODO: vconsole font
    - environment/localization
    # TODO: Map folder names
    - environment/xdg_user_dirs

    # Setup boot
    # TODO: add theme
    - boot/grub

    # Install and setup commandline tools
    - cli/git
    - cli/ssh
    # TODO: setup fzf
    - cli/fzf
    # - cli/man

    # Install and setup shell
    # TODO: split vconsole and include font settings
    - zsh

    # Linux console
    # - kmscon?
#
#    # Desktop environment
#    - role: gnome/gnome_shell
#      tags:
#        - laptop
#        - desktop
#    # Virtualization tools
#    - virtualization
