---
# This playbook deploys the whole application stack to virtual machine.

#- import_playbook: playbook_virtualbox_prestart.yml
- import_playbook: playbook.yml
#- name: apply VirtualBox Guest additions
#  hosts: all
#  roles:
#    - virtualization/virtualbox-guest
