---
# This playbook deploys the whole application stack.

- name: Apply common configuration to all nodes # noqa: role-name[path]
  hosts: all
  roles:
    # Setup package management
    - package-management-tools/reflector
    - package-management-tools/paru
    - package-management-tools/flatpak
    - package-management-tools/appimage_support

    # Setup runtime
    - runtime/kernels
    - runtime/env
    - runtime/localization
    - runtime/xdg_user_dirs

    # Hardware
    - hardware/sof_firmware
    - hardware/networkmanager
    - role: hardware/bluez # noqa: role-name[path]
      tags:
        - laptop
        - desktop
    - role: hardware/pipewire # noqa: role-name[path]
      tags:
        - laptop
        - desktop
    - role: hardware/tlp # noqa: role-name[path]
      tags:
        - laptop

    # Setup boot
    - boot/grub

    # Install and setup commandline tools
    - cli/git
    - cli/ssh
    - cli/fzf
    - cli/man

    # Install and setup shell
    - zsh

    # Desktop environment
    - role: gnome/gnome_shell # noqa: role-name[path]
      tags:
        - laptop
        - desktop

    # Virtualization tools
#    - virtualization
