---
# This playbook deploys the whole application stack.

- name: apply common configuration to all nodes
  hosts: all
  roles:
    # Gathering facts and update system
    - prepare
    - build-tools
    - package-management
    - common

    # Graphic subsystem
    - X11

    # Hardware
    - keyboard
    - pulseaudio

    # Desktop environment
    - plasma

    # Applications
    ## Terminal emulator
    - kitty
    - xst

    ## KDE Apps
    - kde-apps
