---
# This playbook deploys the whole application stack.
- name: Apply common configuration to all nodes
  hosts: all
  roles:
    # System folders
    ## Setup $PATH
    - environment/path
    ## Setup XDG basedir
    - environment/xdg_basedir

    # Package management
    ## Update package database
    - package-management/update
    ## Setup pacman mirror list
    - package-management/reflector
    ## Setup AUR helper
    - package-management/build_tools
    - package-management/paru
    ## Upgrade system
    - package-management/upgrade

    # Default CLI editor
    - environment/default_cli_text_editor

    # Linux Kernels
    - role: kernels/linux
      tags:
        - laptop
        - desktop
    - role: kernels/linux_lts
      tags:
        - virtualbox
    - role: kernels/linux_lqx
      tags:
        - av-production

#    # Hardware
#    - hardware/networkmanager
#    - role: hardware/sof_firmware
#      tags:
#        - laptop
#        - desktop
#    - role: hardware/pipewire
#      tags:
#        - laptop
#        - desktop
#    - role: hardware/bluez
#      tags:
#        - laptop
#        - desktop
#    - role: hardware/tlp
#      tags:
#        - laptop
#    # Linux console
#    # - kmscon?
#    # Languages and Localization
#    - environment/localization
#    - environment/xdg_user_dirs
#    # Setup boot
#    - boot/grub
#
#    # Install and setup commandline tools
#    - cli/git
#    - cli/ssh
#    - cli/fzf
#    - cli/man
#
#    # Install and setup shell
#    - zsh
#
#    # Desktop environment
#    - role: gnome/gnome_shell
#      tags:
#        - laptop
#        - desktop
#    # Virtualization tools
#    - virtualization
