---
# This playbook deploys the whole application stack.

- name: apply common configuration to all nodes
  hosts: all
  roles:
    # Common tasks
    - facts
    - ssh
    - git
    - yay # git role required
    - fonts # yay role required
    - zsh

    # GUI
    #- vga
    ## X11 server
    ## TODO: add standalone compositor for Xorg (https://wiki.archlinux.org/index.php/Picom)
    - xorg
    ## Display manager
    - lightdm
    ## Window manager
    - i3
    ## Hotkey daemon
    - sxhkd
    ## Panel
    - polybar # {yay,i3} role required
    ## Launcher
    - rofi

    # Common applications
    ## Terminal emulator
    - kitty
