---
# This playbook deploys the whole application stack.
- name: Apply common configuration to all nodes # noqa: role-name[path]
  hosts: all
  roles:
    # System folders
    ## Setup $PATH
    - environment/path
    ## Setup XDG basedir
    - environment/xdg_basedir
    # Package management
    ## Upgrade system packages
    - package-management/upgrade_system_packages
    ## Setup pacman mirror list
    - package-management/reflector
    ## Setup additional installation tools
    - package-management/paru
    - package-management/flatpak
    - package-management/appimage_support
    ## Upgrade AUR packages
    - package-management/upgrade_aur_packages
    ## Upgrade Flatpak packages
    - package-management/upgrade_flatpak_packages
    # Default CLI editor
    - environment/default_cli_text_editor

    # Linux Kernels
    - role: kernels/linux # noqa: role-name[path]
      tags:
        - laptop
        - desktop
    - role: kernels/linux_lts # noqa: role-name[path]
      tags:
        - virtualbox
    - role: kernels/linux_lqx # noqa: role-name[path]
      tags:
        - av-production

    # Hardware
    - hardware/networkmanager
    - role: hardware/sof_firmware # noqa: role-name[path]
      tags:
        - laptop
        - desktop
    - role: hardware/pipewire # noqa: role-name[path]
      tags:
        - laptop
        - desktop
    - role: hardware/bluez # noqa: role-name[path]
      tags:
        - laptop
        - desktop
    - role: hardware/tlp # noqa: role-name[path]
      tags:
        - laptop
#    # Linux console
#    # - kmscon?
#    # Languages and Localization
#    - environment/localization
#    - environment/xdg_user_dirs
#    # Setup boot
#    - boot/grub
#
#    # Install and setup commandline tools
#    - cli/git
#    - cli/ssh
#    - cli/fzf
#    - cli/man
#
#    # Install and setup shell
#    - zsh
#
#    # Desktop environment
#    - role: gnome/gnome_shell  # noqa: role-name[path]
#      tags:
#        - laptop
#        - desktop
#    # Virtualization tools
#    - virtualization
