---
# This playbook deploys the whole application stack.

- name: apply common configuration to all nodes
  hosts: all
  roles:
    # Upgrade and prepare system
    - upgrade
    - build-tools
    - package-management
    - common

    # Hardware
    - hardware-support

    # Desktop environment
    - gnome

    ## Virtualization tools
    - virtualization
