---
# This playbook deploys the whole application stack.

- name: apply common configuration to all nodes
  hosts: all
  roles:
    # Gathering facts and update system
    - prepare

    # Common tasks
    - curl
    - ssh
    - git

    # Setup programming languages and build tools
    - pip
    - rust

    # Package management
    - paru # git role required

    # Shell setup
    - zsh

    # Graphic subsystem tasks
    ## X11 server
    - xorg
    ## Display manager
    - lightdm
    ## Window manager
    - awesome

    # Applications
    ## Terminal emulator
    - kitty
