---
# This playbook deploys the whole application stack.

- name: Apply common configuration to all nodes # noqa: role-name[path]
  hosts: all
  roles:
    # Setup package management
    ## Upgrade system packages
    - package-management/upgrade_system_packages
    ## Setup pacman mirror list
    - package-management/reflector
    ## Setup additional installation tools
    - package-management/paru
    - package-management/flatpak
    - package-management/appimage_support
    ## Upgrade AUR packages
    - package-management/upgrade_aur_packages
    ## Upgrade Flatpak packages
    - package-management/upgrade_flatpak_packages

    # Setup environment
    - environment/kernels
    - environment/env
    - environment/localization
    - environment/xdg_user_dirs

    # Hardware
    - hardware/sof_firmware
    - hardware/networkmanager
    - role: hardware/bluez # noqa: role-name[path]
      tags:
        - laptop
        - desktop
    - role: hardware/pipewire # noqa: role-name[path]
      tags:
        - laptop
        - desktop
    - role: hardware/tlp # noqa: role-name[path]
      tags:
        - laptop

    # Setup boot
    - boot/grub

    # Install and setup commandline tools
    - cli/git
    - cli/ssh
    - cli/fzf
    - cli/man

    # Install and setup shell
    - zsh

    # Desktop environment
    - role: gnome/gnome_shell # noqa: role-name[path]
      tags:
        - laptop
        - desktop

    # Virtualization tools
#    - virtualization
