---
# This playbook deploys the whole application stack.

- name: apply common configuration to all nodes
  hosts: all
  roles:
    # Common tasks
    - facts
    - git
    - ssh
    - zsh
    - yay

    # GUI
    #- vga
    # X11 server
    # TODO: add standalone compositor for Xorg (https://wiki.archlinux.org/index.php/Picom)
    - xorg
    # Display manager
    - lightdm
    # Window manager
    - i3
    # Panel
#    - polybar
# Launcher
#    - rofi
