---
# This playbook deploys the whole application stack.

- name: Apply common configuration to all nodes
  hosts: all
  roles:
    # Setup package management
    - package-management-tools/reflector
    - package-management-tools/paru
    - package-management-tools/flatpak
    - package-management-tools/appimage-support

    # Setup runtime
    - runtime/kernels
    - runtime/env
    - runtime/localization
    - runtime/xdg-user-dirs

    # Hardware
    - hardware/sof-firmware
    - hardware/networkmanager
    - role: hardware/bluez
      tags:
        - laptop
        - desktop
    - role: hardware/pipewire
      tags:
        - laptop
        - desktop
    - role: hardware/tlp
      tags:
        - laptop

    # Setup boot
    - boot/grub

    # Install and setup commandline tools
    - cli/git
    - cli/ssh
    - cli/common-cli-tools
    - cli/man

    # Install and setup shell
    - zsh

    # Desktop environment
    - role: gnome/gnome-shell
      tags:
        - laptop
        - desktop

    # Virtualization tools
#    - virtualization
