---
# tasks file for rust
# https://www.rust-lang.org/tools/install
- name: check that the Cargo already local installed
  stat:
    path: ~/.cargo/bin
  register: cargo_stat_result

- name: install Rust
  shell: |
    set -o pipefail
    curl --proto '=https' --tlsv1.2  https://sh.rustup.rs -sSf | sh -s -- -y
  when: cargo_stat_result.stat.exists == false

- name: copy ~/.config/profile.d
  copy:
    src: home/.config/profile.d
    dest: ~/.config/

- name: update Rust tools
  shell: >
    source ~/.profile && rustup update
  args:
    executable: /usr/bin/bash
  when: cargo_stat_result.stat.exists == true
  changed_when: false
