---
# vars file for "gnome_appearance" role
gnome_appearance_packages:
  - "gnome-backgrounds"

gnome_appearance_gtk_theme: "{{ gnome_appearance_default_gtk_theme }}"
gnome_appearance_gtk_theme_role_map:
  "adw-gtk3": "gtk/adw_gtk3"
  "adw-gtk3-dark": "gtk/adw_gtk3"
gnome_appearance_gtk_color_scheme_map:
  "adw-gtk3": "'default'"
  "adw-gtk3-dark": "'prefer-dark'"
gnome_appearance_gtk_color_scheme: "{{ gnome_appearance_gtk_color_scheme_map[gnome_appearance_gtk_theme] }}"

gnome_appearance_icon_theme: "{{ gnome_appearance_default_icon_theme }}"
gnome_appearance_icon_theme_role_map:
  "Papirus": "icons/papirus_icon_theme"
  "Papirus-Light": "icons/papirus_icon_theme"
  "Papirus-Dark": "icons/papirus_icon_theme"

gnome_appearance_upgrade_command_map:
  "Black Box": "blackbox -- /bin/sh -c \"paru -Syu ; echo Done - Press enter to exit; read _\""
  "GNOME Console": "kgx -- /bin/sh -c \"paru -Syu\""
  "Tilix": "tilix -a app-new-window -x \"sudo pacman -Syu\""
  "Kitty": "kitty --detach --directory=\"~\" --hold sh -c \"paru -Syu ; echo Done - Press enter to exit; read _; exit\""

gnome_appearance_upgrade_command: "{{ gnome_appearance_upgrade_command_map[default_terminal_emulator] }}"
