- name: Configure keyboard shortcuts
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
      value:
        "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/tilix-quake-mode/',
        '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"
    - key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/tilix-quake-mode/name"
      value: "'Tilix Quake mode'"
    - key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/tilix-quake-mode/command"
      value: "'tilix --quake'"
    - key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/tilix-quake-mode/binding"
      value: "'<Ctrl><Shift>space'"

- name: advanced keyboard options
  community.general.dconf:
    key: /org/gnome/desktop/input-sources/xkb-options
    value: "['grp_led:scroll', 'compose:ralt', 'grp:caps_toggle']"
