---
- name: "Run a password manager role"
  ansible.builtin.include_role:
    name: "applications/bitwarden"

- name: "Run a 2FA code generator role"
  ansible.builtin.include_role:
    name: "applications/authenticator"
