---
# Update indicator for Arch Linux and GNOME Shell
# https://github.com/RaphaelRochet/arch-update
- name: "Install dependencies"
  become: true
  community.general.pacman:
    name:
      - "pacman-contrib"
    extra_args: "--needed"

- name: "Install and enable 'Arch Update' extension"
  ansible.builtin.include_role:
    name: "gnome/gnome_shell_extension"
  vars:
    # https://extensions.gnome.org/extension/1010/archlinux-updates-indicator/
    gnome_shell_extension_id: "1010"

- name: "Configure 'Arch Update'"
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - key: "/org/gnome/shell/extensions/arch-update/show-count"
      value: "false"
    - key: "/org/gnome/shell/extensions/arch-update/always-visible"
      value: "false"
    - key: "/org/gnome/shell/extensions/arch-update/use-buildin-icons"
      value: "false"
    - key: "/org/gnome/shell/extensions/arch-update/notify"
      value: "true"
    - key: "/org/gnome/shell/extensions/arch-update/howmuch"
      value: "0"
    - key: "/org/gnome/shell/extensions/arch-update/strip-versions-in-notification"
      value: "false"
      # gnome-terminal -- /bin/sh -c "sudo pacman -Syu ; echo Done - Press enter to exit; read _"
    - key: "/org/gnome/shell/extensions/arch-update/update-cmd"
      value: "'{{ gnome_appearance_upgrade_command }}'"
