---
# Display the user avatar in the Quick Settings menu, part of the "System" settings
# https://github.com/d-go/quick-settings-avatar
- name: "Install and enable 'Quick Settings Avatar' extension"
  ansible.builtin.include_role:
    name: "gnome/gnome_shell_extension"
  vars:
    # https://extensions.gnome.org/extension/5506/user-avatar-in-quick-settings/
    gnome_shell_extension_id: "5506"

- name: "Configure 'Quick Settings Avatar'"
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - key: "/org/gnome/shell/extensions/quick-settings-avatar/avatar-position"
      value: "1"
    - key: "/org/gnome/shell/extensions/quick-settings-avatar/avatar-size"
      value: "43"
    - key: "/org/gnome/shell/extensions/quick-settings-avatar/avatar-realname"
      value: "true"
    - key: "/org/gnome/shell/extensions/quick-settings-avatar/avatar-realname"
      value: "true"
    - key: "/org/gnome/shell/extensions/quick-settings-avatar/avatar-username"
      value: "true"
    - key: "/org/gnome/shell/extensions/quick-settings-avatar/avatar-hostname"
      value: "true"
    - key: "/org/gnome/shell/extensions/quick-settings-avatar/avatar-nobackground"
      value: "true"
