---
# tasks file for {{ cookiecutter.role_name }}
- name: Install dependencies
  become: true
  community.general.pacman:
    name: "{{ '{{' }} {{ cookiecutter.role_name|replace('-', '_') }}_packages {{ '}}' }}"
