---
galaxy_info:
  author: Vyacheslav Shimarulin
  description: Setup environment variables
  license: MIT
  min_ansible_version: 2.8

  # Platforms is a list of platforms, and each platform has a name and a list of versions.
  platforms:
    - name: ArchLinux
      versions:
        - all

  galaxy_tags: []
  # List tags for your role here, one per line. A tag is a keyword that describes
  # and categorizes the role. Users find roles by searching for tags. Be sure to
  # remove the '[]' above, if you add tags to this list.
  #
  # NOTE: A tag is limited to a single word comprised of alphanumeric characters.
  #       Maximum 20 tags per role.

dependencies: []
