---
# tasks file for paru
- name: Check that the Paru already installed
  stat:
    path: /usr/bin/paru
  register: paru_stat_result

- name: Get source from AUR
  become: yes
  shell: rm -rf /tmp/paru && git clone https://aur.archlinux.org/paru.git
  args:
    chdir: /tmp
    executable: /usr/bin/bash
  when: paru_stat_result.stat.exists == false

- name: Recursively change ownership of the source directory
  become: yes
  file:
    path: /tmp/paru
    state: directory
    recurse: yes
    owner: '{{ ansible_user_id }}'
    group: '{{ ansible_user_id }}'
  when: paru_stat_result.stat.exists == false

- name: Make and install
  shell: makepkg -si --noconfirm
  args:
    chdir: /tmp/paru
    executable: /bin/bash
  when: paru_stat_result.stat.exists == false
# TODO: add alias like 'pkg update', 'pkg upgrade', 'pkg install', 'pkg install-alternative'?

- name: Update AUR packages cache and upgrade packages
  kewlfft.aur.aur:
    use: paru
    update_cache: yes
    upgrade: yes
  when: paru_stat_result.stat.exists == true
