---
# vars file for nautilus
nautilus_packages:
  - "nautilus"
  - "nautilus-python"

  # Preview and thumbnail tools
  - "sushi"
  - "ffmpegthumbnailer"

  # Compare files and Git integration
  - "meld" # required by "nautilus-compare" or "turtle"
  # - "nautilus-compare" # AUR
  - "turtle" # AUR, replace "nautilus-compare" TODO:FIX: ./workstation/venv/bin/python: No module named build
  - "seahorse" # sign commits TODO: move to "git" role?

  # Utils
  - "nautilus-copy-path"
  # - "actions-for-nautilus-git"

# Extra (AUR)
#  - nautilus-open-any-terminal
#  - nautilus-terminal
#  - gtkhash
#  - nautilus-metadata-editor
#  - nautilus-ext-git
#  - git-nautilus-icons
#  - nautilus-annotations
#  - nautilus-folder-icons
#  - gvfs
#  - gvfs-afc
#  - gvfs-goa
#  - gvfs-google
#  - gvfs-gphoto2
#  - gvfs-mtp
#  - gvfs-nfs
#  - gvfs-smb

nautilus_terminal_emulator_executable_command_map:
  "Black Box": "/usr/bin/blackbox"
  "GNOME Console": "/usr/bin/kgx"
  "Tilix": "/usr/bin/tilix"
  "Kitty": "/usr/bin/kitty --detach"

nautilus_terminal_emulator_executable_command: "{{ nautilus_terminal_emulator_executable_command_map[default_terminal_emulator] }}"
