---
# tasks file for paru
# TODO: add alias like 'pkg update', 'pkg upgrade', 'pkg install', 'pkg install-alternative'?
- name: "Check that the Paru already installed"
  ansible.builtin.stat:
    path: "/usr/bin/paru"
  register: "paru_stat_result"

- name: "Get source from AUR"
  ansible.builtin.shell: "rm -rf /tmp/paru-bin && git clone https://aur.archlinux.org/paru-bin.git"
  args:
    chdir: "/tmp"
    executable: "/usr/bin/bash"
  when: "not paru_stat_result.stat.exists"
  register: "paru_get_result"
  changed_when: "paru_get_result.rc is defined and paru_get_result.rc == 0"

- name: "Make and install"
  ansible.builtin.shell: "makepkg -si --noconfirm"
  args:
    chdir: "/tmp/paru-bin"
    executable: "/bin/bash"
  register: "paru_install_result"
  when: "paru_get_result.rc is defined and paru_get_result.rc == 0"
  changed_when: "paru_install_result.rc is defined and paru_install_result.rc == 0"
