---
# tasks file for firefox
- name: install dependencies
  kewlfft.aur.aur:
    name: '{{ firefox_packages }}'
    use: paru

- name: enable smooth scroll in Firefox
  become: true
  copy:
    src: etc/profile.d/
    dest: /etc/profile.d/

- name: create Firefox global extensions directory if it does not exist
  become: true
  file:
    path: /usr/lib/firefox/browser/extensions/
    state: directory

- name: copy global pref
  become: true
  copy:
    src: usr/lib/firefox/defaults/pref/autoconfig.js
    dest: /usr/lib/firefox/defaults/pref/

- name: copy Firefox global config
  become: true
  copy:
    src: usr/lib/firefox/firefox.cfg
    dest: /usr/lib/firefox/

# https://addons.mozilla.org/en-US/firefox/addon/profile-switcher/
- name: install 'Profile Switcher for Firefox' extension
  become: true
  get_url:
    url: https://addons.mozilla.org/firefox/downloads/file/3809893/
    dest: /usr/lib/firefox/browser/extensions/profile-switcher-ff@nd.ax.xpi
  ignore_errors: true

# https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/
- name: install 'uBlock Origin' Firefox extension
  become: true
  get_url:
    url: https://addons.mozilla.org/firefox/downloads/file/3853583/
    dest: /usr/lib/firefox/browser/extensions/uBlock0@raymondhill.net.xpi
  ignore_errors: true

# https://addons.mozilla.org/ru/firefox/addon/bitwarden-password-manager/
- name: install 'Bitwarden password manager' Firefox extension
  become: true
  get_url:
    url: https://addons.mozilla.org/firefox/downloads/file/3859577/
    dest: /usr/lib/firefox/browser/extensions/{446900e4-71c2-419f-a6a7-df9c091e268b}.xpi
  ignore_errors: true
