# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins]

# Completions
# NOTE: Try:
# - https://github.com/zdharma/zzcomplete
# -----------

# https://github.com/zsh-users/zsh-completions
[plugins.zsh-completions]
git = 'https://github.com/zsh-users/zsh-completions'

# https://github.com/ohmyzsh/ohmyzsh/blob/master/lib/completion.zsh
[plugins.completion]
git = 'https://github.com/ohmyzsh/ohmyzsh'
dir = "lib"

# History
# NOTE: Try
# - https://github.com/zdharma/history-search-multi-word
# -----------

# https://github.com/ohmyzsh/ohmyzsh/blob/master/lib/history.zsh
# The history plugin doesn't like being deferred, not sure why.
[plugins.history]
git = 'https://github.com/ohmyzsh/ohmyzsh'
dir = "lib"

# Oh My Zsh
# -----------

# https://github.com/ohmyzsh/ohmyzsh
[plugins.ohmyzsh]
git = 'https://github.com/ohmyzsh/ohmyzsh.git'
use = ['lib/{key-bindings}.zsh', 'plugins/{command-not-found}/*.plugin.zsh']

# Themes
# NOTE: Try:
# - https://github.com/romkatv/powerlevel10k
# - https://github.com/starship/starship
# - https://github.com/spaceship-prompt/spaceship-prompt
#     TOP CON
#     Really slow when working with kubernetes or big repositories
# -----------

# https://github.com/sindresorhus/pure
#     TOP CON
#     •••
#     Inflexible
#     Configuration options are very limited
#[plugins.purerc]
#local = "~/.config/zsh/themes"
[plugins.pure]
git = "https://github.com/sindresorhus/pure"
use = ["{async,pure}.zsh"]

# Highlighting
# -----------

# https://github.com/zdharma/fast-syntax-highlighting
# NOTE: Run `fast-theme -l` to list available themes.
[plugins.fast-syntax-highlighting]
git = 'https://github.com/zdharma/fast-syntax-highlighting'

# compinit
# -----------

# https://github.com/rossmacarthur/sheldon/issues/122#issuecomment-887258527
# https://github.com/rossmacarthur/dotfiles/blob/trunk/src/zsh/plugins/compinit.plugin.zsh
[plugins.compinit]
local = "~/.config/zsh/plugins"
