- name: install appearance dependencies
  become: true
  pacman:
    name: "{{ gnome_appearance_packages }}"

- name: set GTK and Gnome Shell theme
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - key: "/org/gnome/shell/extensions/user-theme/name"
      value: "'Arc-Dark'" # Arc-Dark-solid
    - key: "/org/gnome/desktop/interface/gtk-theme"
      value: "'Arc-Dark'" # Arc-Darker-solid
    - key: "/org/gnome/desktop/interface/icon-theme"
      value: "'Papirus-Dark'"

# To GTK4 apps
- name: add $GTK_THEME environment variable
  blockinfile:
    path: ~/.pam_environment
    create: true
    marker: "# {mark} ANSIBLE MANAGED BLOCK @gtk-theme"
    block: |
      GTK_THEME=Arc-Dark

- name: copy themes for use by Flatpak applications
  copy:
    src: /usr/share/themes/
    dest: ~/.themes
    remote_src: yes

- name: set Flatpack filesystem
  become: true
  command: 'flatpak override --filesystem={{ ansible_user_dir }}/.themes'
  changed_when: false

- name: set Flatpack applications GTK theme
  become: true
  command: 'flatpak override --env=GTK_THEME=Arc-Dark'
  changed_when: false

- name: set GDM theme
  become: true
  command: 'set-gdm-theme set Arc-Dark'
  changed_when: false

- name: set GDM icon theme
  become: true
  command: 'sudo -u gdm dbus-launch gsettings set org.gnome.desktop.interface icon-theme "Papirus-Dark"'
  changed_when: false

- name: configure panel DateTime
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - key: "/org/gnome/desktop/interface/clock-show-date"
      value: "true"
