---
# tasks file for zsh
# TODO: set zsh as default shell for new users (skeleton)
- name: install dependencies
  become: true
  pacman:
    name: '{{ zsh_packages }}'

- include_tasks: sheldon.yml

- name: set ~/.zshenv
  copy:
    src: home/.zshenv
    dest: ~/.zshenv

- name: set ~/.zshrc
  copy:
    src: home/.zshrc
    dest: ~/.zshrc

# "username" variable is defined in "prepare" role
- name: set zsh as default shell
  user:
    name: '{{ username.stdout }}'
    shell: /usr/bin/zsh
  become: true

- name: synchronize the pkgfile database
  become: true
  command: 'pkgfile -u'
  changed_when: false

- name: enable automatically synchronizing the pkgfile database
  become: true
  systemd:
    name: pkgfile-update.timer
    state: started
    enabled: yes
