# https://github.com/rossmacarthur/sheldon
- name: install build dependencies
  become: true
  pacman:
    name:
      - curl
      - bash
    extra_args: --needed

- name: check that the sheldon already local installed
  stat:
    path: ~/.local/bin/sheldon
  register: sheldon_stat_result

- name: install sheldon
  shell: |
    set -o pipefail
    curl --proto '=https' -fLsS https://rossmacarthur.github.io/install/crate.sh | bash -s -- --repo rossmacarthur/sheldon --to ~/.local/bin
  when: sheldon_stat_result.stat.exists == false

- name: copy config file
  copy:
    src: home/.config/sheldon/plugins.toml
    dest: ~/.config/sheldon/ # If dest is a non-existent path and if either dest ends with "/" or src is a directory, dest is created.

- name: create data directory
  file:
    path: ~/.local/share/sheldon
    state: directory
