---
galaxy_info:
  author: "Vyacheslav Shimarulin"
  description: "Linux Kernel Stable - Vanilla Linux kernel and modules, with a few\
    \ patches applied"
  license: "MIT"
  min_ansible_version: "2.8"

  # Platforms is a list of platforms, and each platform has a name and a list of versions.
  platforms:
    - name: "ArchLinux"
      versions:
        - "all"

dependencies: []
