---
# tasks file for nautilus
- name: Install dependencies
  become: true
  community.general.pacman:
    name: '{{ nautilus_packages }}'

- name: Setup Nautilus (Gnome Files)
  community.general.dconf:
    key: '{{ item.key }}'
    value: '{{ item.value }}'
  loop:
    - key: '/org/gnome/nautilus/preferences/default-folder-viewer'
      value: "'list-view'"

    # Not available now, coming in GNOME 44
    - key: '/org/gnome/nautilus/list-view/use-tree-view'
      value: 'true'

    - key: '/org/gnome/nautilus/list-view/default-zoom-level'
      value: "'small'"

    - key: '/org/gtk/gtk4/settings/file-chooser/sort-directories-first'
      value: 'true'

    - key: '/org/gtk/gtk4/settings/file-chooser/show-hidden'
      value: 'true'
