---
# vars file for "default_terminal_emulator" role
default_terminal_emulator_packages: []

default_terminal_emulator_packages_map:
  "Black Box": "blackbox-terminal"
  "GNOME Console": "gnome-console"
  "Tilix": "tilix"

default_terminal_emulator_executable_paths_map:
  "Black Box": "/usr/bin/blackbox"
  "GNOME Console": "/usr/bin/kgx"
  "Tilix": "/usr/bin/tilix"

default_terminal_emulator_package: "{{ default_terminal_emulator_packages_map[default_terminal_emulator] }}"
default_terminal_emulator_executable_path: "{{ default_terminal_emulator_executable_paths_map[default_terminal_emulator] }}"
default_terminal_emulator_role: "applications/{{ default_terminal_emulator_package | replace('-', '_') }}"
