---
# tasks file for i3
- name: install dependencies
  become: true
  pacman:
    name: "{{ i3_packages }}"

- name: check that the i3 config exist
  stat:
    path: ~/.config/i3/config
  register: i3_config_stat_result

- name: create i3 config directory
  file:
    path: ~/.config/i3
    state: directory
    mode: "755"
  when: i3_config_stat_result.stat.exists == false

- name: create i3 config
  file:
    path: ~/.config/i3/config
    state: touch
  when: i3_config_stat_result.stat.exists == false

- name: insert/update main i3 configuration
  blockinfile:
    path: ~/.config/i3/config
    marker: "# {mark} main i3 configuration"
    marker_begin: "Begin"
    marker_end: "End"
    block: "{{ lookup('file', '.config/i3/blocks/main.i3config') }}"

- name: "insert/update i3 keybindings (TODO: move to `sxhkd`)"
  blockinfile:
    path: ~/.config/i3/config
    marker: "# {mark} i3 keybindings"
    marker_begin: "Begin"
    marker_end: "End"
    block: "{{ lookup('file', '.config/i3/blocks/keybindings.i3config') }}"

# TODO: move to common role
#- name: create user executable scripts directory
#  file:
#    path: ~/.local/bin
#    state: directory
#    mode: "755"

- name: copy XDG autostart launcher
  copy:
    src: .config/i3/autostart.sh
    dest: ~/.config/i3/autostart.sh
    mode: "755"

- name: add XDG autostart init
  blockinfile:
    path: ~/.config/i3/config
    marker: "# {mark} XDG autostart"
    marker_begin: "Begin"
    marker_end: "End"
    block: |
      exec --no-startup-id $HOME/.config/i3/autostart.sh
