---
# tasks file for gnome_shell

- name: Minimal GNOME shell installation
  ansible.builtin.include_role:
    name: gnome/gnome_shell_base # noqa: role-name[path]

- name: Install terminal emulator
  ansible.builtin.include_role:
    name: applications/tilix # noqa: role-name[path]

- name: Install file management tools
  ansible.builtin.include_tasks: file-management-tools.yml
