---
# tasks file for bluez
- name: Install dependencies
  become: true
  community.general.pacman:
    name: '{{ bluez_packages }}'

- name: Add the user to 'lp' group
  become: true
  user:
    name: '{{ ansible_user_id }}'
    groups: lp
    append: yes

- name: Enable bluetooth service
  become: true
  systemd:
    name: bluetooth.service
    state: started
    enabled: yes
