---
# tasks file for nvm

# - name: "Check that the nvm already installed"
#  ansible.builtin.stat:
#    path: "{{ nvm_source_path }}"
#  register: "nvm_installed_stat_result"

- name: "Get nvm latest release info"
  ansible.builtin.uri:
    url: "https://api.github.com/repos/nvm-sh/nvm/releases/latest"
    return_content: true
  register: "nvm_github_latest_release"

- name: "Clone nvm repo"
  ansible.builtin.git:
    repo: "https://github.com/nvm-sh/nvm.git"
    dest: "~/{{ nvm_rel_dir }}"
    version: "{{ nvm_github_latest_release.json.tag_name }}"

# TODO: move to different role (zsh? new role?)
- name: "Create the profile.d user directory"
  ansible.builtin.file:
    path: "~/.config/profile.d"
    state: "directory"
    mode: "u=rwx,g=rwx,o=rx"

- name: "Create the nvm register script"
  ansible.builtin.template:
    src: "home/.config/profile.d/00.nvm.sh.j2"
    dest: "~/.config/profile.d/00.nvm.sh"
    mode: "u=rw,g=r,o=r"
