---
# tasks file for nvm
- name: Get nvm latest release info
  uri:
    url: https://api.github.com/repos/nvm-sh/nvm/releases/latest
    return_content: true
  register: nvm_github_latest_release

- name: Create nvm dir
  shell: >
    mkdir -p $NVM_DIR
  environment: "{{ nvm_env }}"
  changed_when: false

- name: Install latest nvm release
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/{{ nvm_github_latest_release.json.tag_name }}/install.sh |
    bash
  args:
    creates: "{{ nvm_source_path }}"
  environment: "{{ nvm_env }}"

- name: Copy ~/.config/profile.d
  copy:
    src: home/.config/profile.d
    dest: ~/.config/

#- name: loads nvm
#  blockinfile:
#    path: ~/.profile
#    marker: '# {mark} ANSIBLE MANAGED BLOCK @nvm'
#    block: |
#      export NVM_DIR="$HOME/.config/nvm"
#      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

- name: Install latest Node.js
  shell: >
    source ~/.profile && nvm install node
  args:
    executable: /usr/bin/bash
  environment: "{{ nvm_env }}"
  changed_when: false

- name: Enable Corepack
  shell: >
    source ~/.profile && corepack enable
  args:
    executable: /usr/bin/bash
  environment: "{{ nvm_env }}"
  changed_when: false

- name: Prepare and update the "Last Known Good" version of all supported package managers
  shell: >
    source ~/.profile && corepack prepare --all --activate
  args:
    executable: /usr/bin/bash
  environment: "{{ nvm_env }}"
  changed_when: false
