---
# tasks file for git
- name: "Install dependencies"
  become: true
  community.general.pacman:
    name: "{{ git_packages }}"
    extra_args: "--needed"

- name: "Setup default git configuration"
  community.general.git_config:
    name: "{{ item.name }}"
    scope: "global"
    value: "{{ item.value }}"
  with_items:
    - { name: "user.name", value: "{{ git_user_name }}" }
    - { name: "user.email", value: "{{ git_user_email }}" }
    - { name: "core.autocrlf", value: "input" }
    - { name: "ui.color", value: "True" }
    - { name: "init.defaultBranch", value: "main" }
