---
# tasks file for zsh
# TODO: set zsh as default shell for new users (skeleton)
- name: install dependencies
  become: true
  pacman:
    name: '{{ zsh_packages }}'

- include_tasks: sheldon.yml

- name: copy ~/.zshenv
  copy:
    src: home/.zshenv
    dest: ~/.zshenv

- name: copy ~/.config/zsh
  copy:
    src: home/.config/zsh
    dest: ~/.config/

- name: create histdb data directory
  file:
    path: ~/.local/share/histdb
    state: directory

- name: set zsh as default shell
  become: true
  user:
    name: '{{ ansible_user_id }}'
    shell: /usr/bin/zsh

- name: synchronize the pkgfile database
  become: true
  command: 'pkgfile -u'
  changed_when: false

- name: enable automatically synchronizing the pkgfile database
  become: true
  systemd:
    name: pkgfile-update.timer
    state: started
    enabled: yes
