---
# tasks file for upgrade
- name: update archlinux-keyring
  become: true
  command: sudo pacman -Sy archlinux-keyring --noconfirm
  changed_when: false

- name: update pgp-keys database
  become: true
  command: pacman-key --populate archlinux
  changed_when: false

- name: upgrade system
  become: true
  command: pacman -Syu --noconfirm
  changed_when: false

#- name: update packages cache and upgrade system
#  become: true
#  pacman:
#    update_cache: yes
#    upgrade: yes
#  changed_when: false
