---
# tasks file for polybar
- name: check that the Polybar already installed
  stat:
    path: /usr/bin/polybar
  register: polybar_stat_result

- name: install AUR dependencies
  shell: yay -S --noconfirm polybar
  args:
    executable: /bin/bash
  when: polybar_stat_result.stat.exists == false
