---
# tasks file for polybar
- name: check that the Polybar already installed
  stat:
    path: /usr/bin/polybar
  register: polybar_stat_result

- name: install AUR dependencies
  shell: yay -S --noconfirm polybar
  args:
    executable: /bin/bash
  when: polybar_stat_result.stat.exists == false

- name: create polybar config directory
  file:
    path: ~/.config/polybar
    state: directory
    mode: "755"

- name: copy polybar config
  copy:
    src: .config/polybar/config
    dest: ~/.config/polybar/config

- name: copy polybar launcher
  copy:
    src: .config/polybar/launch.sh
    dest: ~/.config/polybar/launch.sh
    mode: "755"
