- name: install Gnome appearance dependencies
  kewlfft.aur.aur:
    name: '{{ gnome_appearance_packages }}'
    use: paru

- name: set Icons, GTK and Gnome Shell theme
  community.general.dconf:
    key: '{{ item.key }}'
    value: '{{ item.value }}'
  loop:
    - key: '/org/gnome/desktop/interface/icon-theme'
      value: "'Papirus-Dark'"
    #    - key: "/org/gnome/shell/extensions/user-theme/name"
    #      value: "'Arc-Dark'" # Arc-Dark-solid
    - key: '/org/gnome/desktop/interface/gtk-theme'
      value: "'adw-gtk3-dark'"

- name: set GDM icon theme
  become: true
  command: 'sudo -u gdm dbus-launch gsettings set org.gnome.desktop.interface icon-theme "Papirus-Dark"'
  changed_when: false

- name: configure panel DateTime
  community.general.dconf:
    key: '{{ item.key }}'
    value: '{{ item.value }}'
  loop:
    - key: '/org/gnome/desktop/interface/clock-show-date'
      value: 'true'
