---
# tasks file for keyboard
- name: check keyboard config file
  stat:
    path: /etc/X11/xorg.conf.d/00-keyboard.conf
  register: keyboard_stat_result

- name: set default keyboard
  become: true
  shell: localectl --no-convert set-x11-keymap us,ru
  when: keyboard_stat_result.stat.exists == false
