- name: create Firefox global extensions directory if it does not exist
  become: true
  file:
    path: /usr/lib/firefox/browser/extensions/
    state: directory

- name: install native connector software for the 'GNOME Shell integration' extension (binary files)
  kewlfft.aur.aur:
    name:
      - gnome-browser-connector
    use: paru

# https://addons.mozilla.org/en-US/firefox/addon/gnome-shell-integration/
- name: install 'GNOME Shell integration' Firefox extension
  become: true
  get_url:
    url: https://addons.mozilla.org/firefox/downloads/file/3974897/
    dest: /usr/lib/firefox/browser/extensions/chrome-gnome-shell@gnome.org.xpi
  ignore_errors: true

# Override Firefox launcher
- name: create temporary Firefox launcher
  copy:
    src: /usr/share/applications/firefox.desktop
    dest: /tmp/firefox.desktop
    remote_src: true
  changed_when: false

- name: add environment variables to Firefox launcher
  lineinfile:
    path: /tmp/firefox.desktop
    regexp: '^Exec=/usr/lib/firefox/firefox %u'
    line: Exec=env GTK_THEME=Arc-Darker /usr/lib/firefox/firefox %u
  changed_when: false

- name: add environment variables to Firefox launcher
  lineinfile:
    path: /tmp/firefox.desktop
    regexp: '^Exec=/usr/lib/firefox/firefox --new-window %u'
    line: Exec=env GTK_THEME=Arc-Darker /usr/lib/firefox/firefox --new-window %u
  changed_when: false

- name: add environment variables to Firefox launcher
  lineinfile:
    path: /tmp/firefox.desktop
    regexp: '^Exec=/usr/lib/firefox/firefox --private-window %u'
    line: Exec=env GTK_THEME=Arc-Darker /usr/lib/firefox/firefox --private-window %u
  changed_when: false

- name: create user defined Firefox launcher
  copy:
    src: /tmp/firefox.desktop
    dest: ~/.local/share/applications/firefox.desktop
    remote_src: true
