#!/bin/bash

# https://www.cyberciti.biz/faq/howto-find-linux-vga-video-card-ram/

VGA_INFO=$(lspci | grep -e VGA -e 3D)

if [[ "$VGA_INFO" == *"Intel"* ]]; then
  if [[ "$VGA_INFO" == *"NVIDIA"* ]]; then
    printf "nvidia-hybrid"
  elif [[ "$VGA_INFO" == *"AMD"* ]]; then
    printf "amd-hybrid"
  elif [[ "$VGA_INFO" == *"ATI"* ]]; then
    printf "amd-hybrid"
  else
    printf "intel"
  fi
elif [[ "$VGA_INFO" == *"NVIDIA"* ]]; then
  printf "nvidia"
elif [[ "$VGA_INFO" == *"AMD"* ]]; then
  printf "amd"
elif [[ "$VGA_INFO" == *"ATI"* ]]; then
  printf "amd"
else
  printf "vesa"
fi
