---
# vars file for "gnome_shell" role
gnome_shell_packages:
  # Core
  - "gnome-shell"

  # A backend implementation for xdg-desktop-portal (a portal frontend service for Flatpak
  # and possibly other desktop containment frameworks) for the GNOME desktop environment
  - "xdg-desktop-portal-gnome"

  # Settings
  - "dconf-editor"
  - "gnome-control-center"
  - "gnome-tweaks"

  # Monitoring
  - "baobab"
  - "gnome-disk-utility"
  - "gnome-logs"
  - "gnome-system-monitor"

  # Media subsystem
  # see https://wiki.archlinux.org/title/GStreamer#Hardware_video_acceleration
  # and https://wiki.archlinux.org/title/Hardware_video_acceleration
  - "gst-libav"
  - "gst-plugin-pipewire"
  - "gst-plugins-bad"
  - "gst-plugins-base"
  - "gst-plugins-good"
  - "gst-plugins-ugly"
  - "gstreamer"
  - "gstreamer-vaapi"

  # Help
  - "gnome-user-docs"
  - "yelp"
