---
# tasks file for lightdm
- name: install dependencies
  become: true
  pacman:
    name: '{{ lightdm_packages }}'

- name: enable LightDM service
  become: true
  systemd:
    name: lightdm.service
    enabled: yes

- name: enable LightDM GTK+ Greeter
  become: true
  lineinfile:
    path: /etc/lightdm/lightdm.conf
    regexp: '^#greeter-session='
    line: greeter-session=lightdm-gtk-greeter

# https://wiki.archlinux.org/index.php/Systemd#Change_default_target_to_boot_into
# systemctl set-default graphical.target
- name: change default target to graphical.target
  become: true
  file:
    src: /usr/lib/systemd/system/graphical.target
    dest: /etc/systemd/system/default.target
    state: link
