---
# tasks file for firefox
- name: install dependencies
  become: true
  pacman:
    name: '{{ firefox_packages }}'

- name: enable smooth scroll
  become: true
  copy:
    src: etc/profile.d/
    dest: /etc/profile.d/

- name: create firefox global extension directory
  become: true
  file:
    path: /usr/lib/firefox/browser/extensions/
    state: directory

- name: copy global pref
  become: true
  copy:
    src: usr/lib/firefox/defaults/pref/autoconfig.js
    dest: /usr/lib/firefox/defaults/pref/

- name: copy global config
  become: true
  copy:
    src: usr/lib/firefox/firefox.cfg
    dest: /usr/lib/firefox/

# TODO: move to KDE
# https://addons.mozilla.org/en-US/firefox/addon/plasma-integration/
#- name: install 'Plasma Integration by KDE' extension
#  become: true
#  get_url:
#    url: https://addons.mozilla.org/firefox/downloads/file/3859385/
#    dest: /usr/lib/firefox/browser/extensions/plasma-browser-integration@kde.org.xpi

- name: install native connector software for the 'Profile Switcher for Firefox' extension (binary files)
  shell: paru -S --noconfirm firefox-profile-switcher-connector-bin
  args:
    executable: /bin/bash
  changed_when: false

# https://addons.mozilla.org/en-US/firefox/addon/profile-switcher/
- name: install 'Profile Switcher for Firefox' extension
  become: true
  get_url:
    url: https://addons.mozilla.org/firefox/downloads/file/3809893/
    dest: /usr/lib/firefox/browser/extensions/profile-switcher-ff@nd.ax.xpi

# https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/
- name: install 'uBlock Origin' extension
  become: true
  get_url:
    url: https://addons.mozilla.org/firefox/downloads/file/3853583/
    dest: /usr/lib/firefox/browser/extensions/uBlock0@raymondhill.net.xpi

# https://addons.mozilla.org/ru/firefox/addon/bitwarden-password-manager/
- name: install 'Bitwarden password manager' extension
  become: true
  get_url:
    url: https://addons.mozilla.org/firefox/downloads/file/3859577/
    dest: /usr/lib/firefox/browser/extensions/{446900e4-71c2-419f-a6a7-df9c091e268b}.xpi
