---
- name: "Run selected GTK Theme role"
  ansible.builtin.include_role:
    name: "{{ gnome_appearance_gtk_theme_role_map[gnome_appearance_gtk_theme] }}"

- name: "Set selected GTK Theme"
  community.general.dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    value: "'{{ gnome_appearance_gtk_theme }}'"
