---
# tasks file for geary
- name: install dependencies
  become: true
  pacman:
    name: "{{ geary_packages }}"

- name: setup Geary
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
#    - key: "/org/gnome/Geary/autoselect"
#      value: "true"
#    - key: "/org/gnome/Geary/display-preview"
#      value: "true"
#    - key: "/org/gnome/Geary/single-key-shortcuts"
#      value: "false"
    - key: "/org/gnome/Geary/startup-notifications"
      value: "true"
#    - key: "/org/gnome/Geary/search-strategy"
#      value: "conservative"
#    - key: "/org/gnome/Geary/window-height"
#      value: "800"
#    - key: "/org/gnome/Geary/window-width"
#      value: "900"
