---
# tasks file for "gnome_shell" role
- name: "Install dependencies"
  become: true
  community.general.pacman:
    name: "{{ gnome_shell_packages }}"
    extra_args: "--needed"

- name: "Run a default terminal emulator role"
  ansible.builtin.include_role:
    name: "environment/default_terminal_emulator"

- name: "Run a Display manager and login screen role"
  ansible.builtin.include_role:
    name: "login/gdm"

- name: "Run an file manager role"
  ansible.builtin.include_role:
    name: "applications/nautilus"

- name: "Run an archive manager role"
  ansible.builtin.include_role:
    name: "applications/file_roller"
