---
galaxy_info:
  author: "Vyacheslav Shimarulin"
  description: "Linux Liquorix Kernel - Linux kernel designed for uncompromised responsiveness\
    \ in interactive systems, enabling low latency compute in A/V production, and\
    \ reduced frame time deviations in games"                                                  # noqa: yaml[line-length]
  license: "MIT"
  min_ansible_version: "2.8"

  # Platforms is a list of platforms, and each platform has a name and a list of versions.
  platforms:
    - name: "ArchLinux"
      versions:
        - "all"

dependencies: []
