---
# tasks file for "pacman" role

- name: "Setup color output"
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/pacman.conf"
    regexp: "^#Color"
    line: "Color"

- name: "Setup parallel downloads"
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/pacman.conf"
    regexp: "^#ParallelDownloads.*"
    line: "ParallelDownloads = 5"
