---
# This playbook deploys the whole application stack.
- name: Apply a common configuration to all nodes
  hosts: all
  roles:
    # System folders
    ## Setup $PATH
    - role: environment/path
    - role: environment/xdg_basedir

    # Package management
    ## Update packages database and upgrade system
    - role: package-management/update
    ## Setup pacman mirror list
    - role: package-management/reflector
    ## Setup AUR helper
    - role: package-management/build_tools
    - role: package-management/paru

    # Setup and create initial ramdisk images for existing Linux kernels if it needs
    - role: boot/mkinitcpio

    # Install Linux Kernels and (re)create initial ramdisk images automatically
    - role: kernels/linux
      tags:
        - laptop
        - desktop
        - kernel-latest
    - role: kernels/linux_lts
      tags:
        - virtualbox
        - kernel-lts
    - role: kernels/linux_lqx
      tags:
        - av-production
        - kernel-lqx

    # Setup boot
    # TODO: add theme
    - role: boot/grub

    # Hardware
    ### Network
    - role: hardware/networkmanager
    ### Sound card firmware
    - role: hardware/sof_firmware
      tags:
        - laptop
        - desktop
    ### Audio
    - role: hardware/pipewire
      tags:
        - laptop
        - desktop
    ### Bluetooth
    - role: hardware/bluez
      tags:
        - laptop
        - desktop
    ### Power management
    - role: hardware/tlp
      tags:
        - laptop

    # Default CLI editor
    - role: environment/default_cli_text_editor

    # Languages and Localization
    # TODO: extract vconsole font
    - role: environment/localization

    # Install and setup commandline tools
    # TODO: setup fzf
    - role: cli/fzf
    # - cli/man

    # Install and setup shell
    # TODO: split vconsole and include font settings
    - role: zsh

    # Linux console
    # - kmscon?
