---
# This playbook deploys the whole application stack.
- name: Include the base play
  ansible.builtin.import_playbook: base.yml

- name: Include the Desktop Environment play
  ansible.builtin.import_playbook: gnome.yml

- name: Apply post-install configuration to all nodes
  hosts: all
  roles:
    # Default VISUAL editor
    - role: environment/default_visual_text_editor

    # XDG user dirs
    - role: environment/xdg_user_dirs
