---
# tasks file for ssh
- name: Install dependencies
  become: true
  community.general.pacman:
    name: '{{ ssh_packages }}'

- name: Create ~/.ssh directory
  ansible.builtin.file:
    path: ~/.ssh
    state: directory
    mode: '0755'

- name: Check that the SSH config already created
  ansible.builtin.stat:
    path: ~/.ssh/config
  register: sshconfig_stat_result

- name: Create SSH config
  ansible.builtin.file:
    path: ~/.ssh/config
    state: touch
    mode: '0600'
  when: not sshconfig_stat_result.stat.exists

- name: Generate ssh keys
  ansible.builtin.include_tasks: generate_key.yml
  loop: '{{ ssh_hosts }}'
