# Install from git
- name: clone Gnome Shell extension repo - {{ item.name }}
  git:
    repo: "{{ item.repo }}"
    depth: 1
    dest: "/tmp/{{ item.name }}"
  when: item.repo is defined

- name: copy Gnome Shell extension source - {{ item.name }}
  command: cp --recursive /tmp/{{ item.name }}{{ item.path }} $HOME/.local/share/gnome-shell/extensions/{{ item.name }}
  when: item.repo is defined

# Install from zip package
- name: create extra directories
  file:
    path: "$HOME/.local/share/gnome-shell/extensions/{{ item.name }}"
    state: directory
  when: item.zip is defined

- name: unarchive remote Gnome Shell extension arhive repo - {{ item.name }}
  ansible.builtin.unarchive:
    src: "{{ item.zip }}"
    dest: "$HOME/.local/share/gnome-shell/extensions/{{ item.name }}"
    remote_src: yes
  when: item.zip is defined

# Install from AUR
- name: install {{ item.name }} from AUR
  command: 'paru -S --noconfirm {{ item.aur }}'
  when: item.aur is defined
  changed_when: false
