---
# tasks file for "upgrade_flatpak_packages" role
- name: Upgrade installed Flatpak packages
  ansible.builtin.command: flatpak update -y
  register: flatpak_update_result
  changed_when: flatpak_update_result.rc == 0
