---
# tasks file for systemd-graphical-target

# https://wiki.archlinux.org/index.php/Systemd#Change_default_target_to_boot_into
# systemctl set-default graphical.target
- name: change default target to graphical.target
  become: true
  file:
    src: /usr/lib/systemd/system/graphical.target
    dest: /etc/systemd/system/default.target
    state: link
