---
# tasks file for ssh
- name: install dependencies
  become: true
  community.general.pacman:
    name: '{{ ssh_packages }}'

- name: create ssh directory
  file:
    path: ~/.ssh
    state: directory

- name: check that the SSH config already created
  stat:
    path: ~/.ssh/config
  register: sshconfig_stat_result

- name: create SSH config
  file:
    path: ~/.ssh/config
    state: touch
    mode: 0600
  when: sshconfig_stat_result.stat.exists == false

- name: generate ssh keys
  include_tasks: generate_key.yml
  loop: '{{ ssh_hosts }}'
