---
# tasks file for fonts
- name: install dependencies
  become: true
  pacman:
    name: "{{ fonts_packages }}"

- name: install AUR dependencies
  shell: "yay -S --noconfirm {{ fonts_aur_packages | join(' ') }}"
  args:
    executable: /bin/bash
  changed_when: false
